# MySQL配置
mysql:
  host: 'localhost'
  user: 'root'
  password: 'password'
  database: 'material'

# MongoDB配置
mongo:
  host: 'localhost'
  port: 27017
  username: 'admin'
  password: 'password'
  authSource: 'admin'
  authMechanism: 'SCRAM-SHA-256'
  maxPoolSize: 1024

# 数据库配置
db:
  mes_db_name: 'MES'

# 集合配置
coll:
  convmaterial_coll_name: 'ConvMaterial'
