# MySQL配置
mysql:
  host: '10.9.36.85'
  user: 'root'
  password: 'password'
  database: 'material'

# MongoDB配置
mongo:
  host: '10.9.36.85'
  port: 27017
  username: 'admin'
  password: 'password'
  authSource: 'admin'
  authMechanism: 'SCRAM-SHA-256'
  maxPoolSize: 1024

# 数据库配置
db:
  mes_db_name: 'MES'

# 集合配置
coll:
  convmaterial_coll_name: 'ConvMaterial'
